TaskManager.MVC5/Models/TaskDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using TaskManager.MVC5.Model;

namespace TaskManager.MVC5.Models
{
    public class TaskDetails
    {
        public Task Task { get; set; }
        public IEnumerable<Status> Statuses { get; set; }
        public TaskDetails(Task ts, IEnumerable<Status> st)
        {
            Task = ts;
            Statuses = st;
        }


    }
}

TaskManager.MVC5/Areas/Admin/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskManager.MVC5.Models;
using System.Net.Mail;

namespace TaskManager.MVC5.Areas.Admin.Controllers
{
    public class EmployeesController : Controller
    {
        private DSSDbContext db = new DSSDbContext();

        // GET: Admin/Employees
        public ActionResult Index()
        {
            var employees = db.Employees.Include(t => t.Skill);
            return View(employees.ToList());
        }
        

        public ActionResult Rank()
        {
            return View(db.Employees.ToList());
        }

        

        // GET: Admin/Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.SkillId = new SelectList(db.Skills, "Id", "SkillName", employee.SkillId);
            return View(employee);
        }

        // GET: Admin/Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(new Employee() {
                    FirstName=employee.FirstName,
                    LastName=employee.LastName,
                    Address=employee.Address,
                    ContactNo=employee.ContactNo,
                    designation=employee.designation,
                    Email=employee.Email,
                    enrollDate=employee.enrollDate,
                    Password=employee.Password,
                    SkillId=employee.SkillId,
                    Status=employee.Status
                });
                
                db.SaveChanges();




                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Admin/Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.SkillId = new SelectList(db.Skills, "Id", "SkillName",employee.SkillId);
            return View(employee);
        }

        // POST: Admin/Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,designation,Address,Email,Password,ContactNo,enrollDate,ModifiedDate,SkillId,Status")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Admin/Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Admin/Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

TaskManager.MVC5/Areas/Admin/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskManager.MVC5.Models;

namespace TaskManager.MVC5.Areas.Admin.Controllers
{
    public class SkillsController : Controller
    {
        private DSSDbContext db = new DSSDbContext();

        // GET: Admin/Skills
        public ActionResult Index()
        {
            return View(db.Skills.ToList());
        }

        // GET: Admin/Skills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skill skill = db.Skills.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }

        // GET: Admin/Skills/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Skills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SkillViewModel skill)
        {
            if (ModelState.IsValid)
            {
                db.Skills.Add(new Skill()
                {
                    SkillName = skill.SkillName,

                    status = skill.status
                });

                db.SaveChanges();




                return RedirectToAction("Index");
            }
            return View(skill);
        }





        // GET: Admin/Skills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skill skill = db.Skills.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }

        // POST: Admin/Skills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SkillName,status")] Skill skill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(skill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(skill);
        }

        // GET: Admin/Skills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Skill skill = db.Skills.Find(id);
            if (skill == null)
            {
                return HttpNotFound();
            }
            return View(skill);
        }

        // POST: Admin/Skills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Skill skill = db.Skills.Find(id);
            db.Skills.Remove(skill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaskManager.MVC5/Controllers/SendMailerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace TaskManager.MVC5.Controllers
{
    public class SendMailerController : Controller
    {
        //
        // GET: /SendMailer/  
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ViewResult Index(TaskManager.MVC5.Models.MailModel _objModelMail)
        {
            if (ModelState.IsValid)
            {
                MailMessage mail = new MailMessage();
                mail.To.Add(_objModelMail.To);
                mail.From = new MailAddress("sandeepmaharjan94@gmail.com");
                mail.Subject = _objModelMail.Subject;
                string Body = _objModelMail.Body;
                mail.Body = Body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential("sandeepmaharjan94@gmail.com", "Kathmandu1111");// Enter seders User name and password
                smtp.EnableSsl = true;
               
                mail.Headers.Add("Disposition-Notification-To", "sandeepmaharjan94@gmail.com");
                mail.DeliveryNotificationOptions = DeliveryNotificationOptions.OnSuccess;
               
                mail.ReplyTo = mail.From;

                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(mail);
                return View("Index", _objModelMail);
            }
            else
            {
                return View();
            }
        }
    }
}

TaskManager.MVC5/Views/System/Employee.cshtml
@{
    ViewBag.Title = "Employee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Index", "SendMailer")'" style='width:100px;height:50px'>Send Mail</button>
   </center>
 @Html.Raw(Model.Render())


    <div id="footer-top-border"></div>
    <script>

    scheduler.attachEvent("onClick", function (id) {
        window.location = '@Url.Action("TaskDetails","System")?id=' + id;
    });
    </script>

TaskManager.MVC5/Views/System/Manager.cshtml
@model TaskManager.MVC5.Controllers.SystemController.SystemModel
@{
    ViewBag.Title = "Manage Tasks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}<br><br>
<center>
    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Index", "Admin/Employees")'" style='width:100px;height:100px'>Employees</button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Admin/Task")'" style='width:100px;height:100px'>Tasks</button>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "Admin/Reports")'" style='width:100px;height:100px'>Reports</button>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "Skills")'" style='width:100px;height:100px'>Skill</button>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Rank", "Employees")'" style='width:100px;height:100px'>Rank</button>
   @*<button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Calender")'" style='width:100px;height:100px'>DssCalender</button>*@
 </center>
@Html.Raw(Model.Scheduler.Render())
<div id="footer-top-border"></div>
<style type="text/css">
    @foreach(var state in Model.Statuses) {
        <text> .dhx_cal_event.state_@state.id div{
            background-color: @state.color;
        }
        </text>
    }
</style>

<script type="text/javascript">
    var data = JSON.parse('@Html.Raw(Model.Users)');
    scheduler.templates.event_header = function (start, end, ev) {
        return scheduler.templates.event_date(start) + " - " + scheduler.templates.event_date(end) + " (" + findById(data, ev.owner_id) + ")";
    };

    function findById(ar, id) {
        for (var i = 0; i < ar.length; i++) {
            if (ar[i].key == id) {
                return ar[i].userName;
            }
        }
        return "";
    }
</script>

TaskManager.MVC5/Views/System/TaskDetails.cshtml
@{
    ViewBag.Title = "TaskDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model TaskManager.MVC5.Models.TaskDetails

<div class="page row">

    <span>@ViewData["user"], TaskDetails</span>


    @if (Model.Task != null)
    {
        using (Html.BeginForm("Index", "System/UpdateStatus", FormMethod.Post, null))
        {
            @Html.Hidden("id", Model.Task.id)

            <div class="center-block">
                <div class=" text-right form-group">
                    <span>

                        @String.Format("{0:MM/dd/yyyy}", Model.Task.start_date),
                        <b>
                            @String.Format("{0:HH:mm}", Model.Task.start_date)
                            &ndash; @String.Format("{0:HH:mm}", Model.Task.end_date)
                        </b>
                    </span>
                </div>
                <div class="text-left dhx_cal_ltext form-group">
                    <h1>@Model.Task.text</h1>
                </div>
                <div class="text-left details form-group">
                    <div @( string.IsNullOrEmpty(Model.Task.details) ? "style= 'color':#bbb;" : "") style="word-wrap: break-word;">@(string.IsNullOrEmpty(Model.Task.details) ? "Task has no description" : Model.Task.details)</div>
                </div>
                <div class="text-left form-group">
                    <span>Status: </span>
                    @Html.DropDownList("status_id", new SelectList(Model.Statuses, "id", "title", ViewData["status"]), new
                    {
                        @class = "dhx_cal_ltext",
                        @style = "width:172px;"
                    })
                </div>

                <div class=" text-center form-group">
                    <input type="submit" name="result" value="Update" class="dhx_btn_set dhx_left_btn_set dhx_save_btn_set" style="width: 70px;" />

                    <input type="submit" name="result" value="Cancel" class="dhx_btn_set dhx_right_btn_set dhx_delete_btn_set " style="float: right; width: 70px;" />
                </div>
            </div>

        }
    }

</div>